AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'random-user

  Sample SAM Template for random-user

  '
Globals:
  Function:
    Runtime: python3.6
    Timeout: 30

Resources:
  DbGet:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: DbGetFunction
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: customers
      Events:
        UserGenerator:
          Type: Api
          Properties:
            Path: /userget
            Method: get
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt UserDatabase.StreamArn
            BatchSize: 100
            StartingPosition: TRIM_HORIZON

  DbPost:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: DbPostFunction
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: customers
      Events:
        UserGenerator:
          Type: Api
          Properties:
            Path: /userpost
            Method: post

  UserGenerator:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: UserGeneratorFunction
      Handler: app.lambda_handler
      Events:
        MachineLearningModel:
          Type: Api
          Properties:
            Path: /user
            Method: get

  MachineLearningModel:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: MachineLearningModelFunction
      Handler: app.lambda_handler
      Events:
        MachineLearningModel:
          Type: Api
          Properties:
            Path: /cluster
            Method: get

  UserDatabase:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: customers
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE
